# Generated by Django 3.0.8 on 2020-07-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200722_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='pending',
        ),
        migrations.AddField(
            model_name='follow',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
